<?php

namespace AppBundle\Repository;

/**
 * FLFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FLFormRepository extends \Doctrine\ORM\EntityRepository
{
}
