<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1qdesv0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1qdesv0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container1qdesv0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container1qdesv0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container1qdesv0\appDevDebugProjectContainer(array(
    'container.build_hash' => '1qdesv0',
    'container.build_id' => 'caecb4c4',
    'container.build_time' => 1522205820,
));
